# Generated by Django 6.0.7 on 2026-07-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project_enrollnment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_enrollnment',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='project_enrollnment',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.project'),
        ),
    ]
