# Generated by Django 6.0.7 on 2026-07-14 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_project_enrollnment_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_enrollnment',
            new_name='Project_enrollment',
        ),
        migrations.RenameField(
            model_name='project_enrollment',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='project_enrollment',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='projects', through='accounts.Project_enrollment', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
